/**
 * Type declaration for the `@/.source` module generated by fumadocs-mdx.
 *
 * `fumadocs-mdx` generates a `.source/index.ts` file at build time (when
 * `next build` or `next dev` runs) that exports `docs` and `blog` collections.
 * The `tsconfig.json` path alias `"@/.source": ["./.source"]` points to it.
 *
 * However, `tsc --noEmit` (run standalone, without the Next.js build step)
 * cannot find the module because `.source/` doesn't exist yet. This ambient
 * declaration silences those false-positive errors during standalone typecheck.
 *
 * At build time, the real generated `.source/index.ts` takes precedence over
 * this ambient declaration (TypeScript resolves the path alias first).
 */

declare module '@/.source' {
  /**
   * Minimal shape matching what `src/lib/source.ts` and `src/lib/blog-source.ts`
   * actually use: they call `.toFumadocsSource()` which returns a `Source`-like
   * object with a `files` property (array or function returning array).
   */
  interface GeneratedCollection {
    toFumadocsSource(): {
      files: any[] | (() => any[]);
    };
  }

  export const docs: GeneratedCollection;
  export const blog: GeneratedCollection;
}
